# Generated by Django 3.2.7 on 2021-09-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='depart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='department_app.department'),
        ),
    ]
