# Generated by Django 3.2.7 on 2021-09-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0002_alter_employees_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department_app.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_app.department'),
        ),
    ]
