# Generated by Django 3.2.5 on 2021-09-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0008_alter_department_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_name', to='department_app.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to='department_app.department'),
        ),
    ]
