# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2   
     - name: Set up Python 3.8
       uses: actions/setup-python@v1
       with:
            python-version: 3.8
     - name: Install dependencies
       run: |
          python -m pip install --upgrade pip
          pip install pylint
     - name: Analysing the code with pylint
       run: |
          find . -name '*.py' -exec pylint {} \;
     - name: Install coverage
       run: | 
        pip install coverage
        coverage run --source=department_project department_project/manage.py test department_app
     - name: Install Coveralls
       run:  pip install coveralls
       
     - name: Coveralls GitHub Action
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: coveralls --service=github

      
    
